on: [ pull_request ]

jobs:
  find_changed_lines:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - name: Find changed lines
        id: changed_lines
        uses: hestonhoffman/changed-lines@v1

      - name: Install uv environment
        uses: astral-sh/setup-uv@v4

      - name: Install ilamb3 and dependencies
        run: uv sync

      - name: Operate on changed lines
        run: uv run python scripts/validate_patch.py $GITHUB_OUTPUT
